version: '3.8'

services:
  frontend:
   build: ./frontend
   ports:
   - "5173:5173"
   depends_on:
   - backend
   networks:
   - mynet
   environment:
   - VITE_API_URL=http://backend:3000
  backend:
   build: ./server
   ports:
   - "3000:3000"
   depends_on:
   - mongo
   environment:
   - MONGO_URI=mongodb://mongo:27017/mydb
   networks:
   - mynet

  mongo:
   image: mongo:latest
   ports:
   - "27017:27017"
   volumes:
   - mongo-data:/data/db
   networks:
   - mynet

volumes:
  mongo-data:

networks:
  mynet:
  