name: Docker CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start containers
        run: docker-compose up -d --build

      - name: Wait for backend to be ready
        run: |
          echo "Waiting for backend service..."
          sleep 10
          curl --retry 5 --retry-delay 5 --retry-all-errors http://localhost:3000 || exit 1

      - name: Check frontend build (optional)
        run: docker exec $(docker ps -qf "ancestor=frontend") npm run build

      - name: Stop containers
        run: docker-compose down
